#include <stdio.h>
#include <string.h>

const int NUM_COUNTRIES = 186;
   
typedef struct Country_struct { //defining struct with different variables to extract differet data from
   char code[4];
   char name[40];
   double ghg; //total greenhouse gas emissions, averaged over 2012-2016; units: million-tonnes of CO2
   double co2; //total carbon dioxide gas emissions, averaged over 2012-2016; units: million-tonnes of CO2
   double ch4; //total methane gas emissions, averaged over 2012-2016; units: million-tonnes of CO2
   double n2o; //total nitrous oxide gas emissions, averaged over 2012-2016; units: million-tonnes of CO2
   double pop; //total population, averaged over 2012-2016
   double gdp; //gross domestic product, averaged over 2012-2016
   double consumption; //total primary energy consumption, averaged over 2012-2016; units: terawatt-hours
   double generation; //total electricity generation, from 2016; units: gigawatt-hours
   double renewable; //electricity generation from renewable sources, from 2016; units: gigawatt-hours
   double hydro; //electricity generation from hydropower, from 2016; units: gigawatt-hours
   double wind; //electricity generation from wind, from 2016; units: gigawatt-hours
   double biomass; //electricity generation from biomass, from 2016; units: gigawatt-hours
   double solar; //electricity generation from solar, from 2016; units: gigawatt-hours
   double geothermal; //electricity generation from geothermal, from 2016; units: gigawatt-hours
} Country;

void printDetails(Country me) {
   printf("Country: %s\n",me.name);
   printf("  Population: %.0lf\n",me.pop);
   printf("  Gross Domestic Product: %.0lf USD\n",me.gdp);   
   printf("  Greenhouse Gas Emissions [in million-tonnes of C02 equivalent]\n");
   printf("    Total: %.2lf\n", me.ghg);
   printf("    Carbon Dioxide: %.2lf\n", me.co2);
   printf("    Methane: %.2lf\n", me.ch4);
   printf("    Nitrous Oxide: %.2lf\n", me.n2o);
   printf("  Total Energy Consumption: %.2lf terawatt-hours\n",me.consumption);
   printf("  Electricity Generation [in gigawatt-hours]\n");
   printf("    Total: %.2lf\n", me.generation);
   printf("    Renewable Sources: %.2lf\n", me.renewable);
   printf("    Hydropower: %.2lf\n", me.hydro);
   printf("    Wind Power: %.2lf\n", me.wind);
   printf("    Biomass: %.2lf\n", me.biomass);
   printf("    Solar Power: %.2lf\n", me.solar);
   printf("    Geothermal: %.2lf\n", me.geothermal);
}

int findCountry(Country all[NUM_COUNTRIES], char* myCode) {//finding the country
   for (int i = 0; i < NUM_COUNTRIES; ++i) {
      if (strcmp(myCode,all[i].code) == 0) {
         return i;
      }
   }
   return -1; //code not found
}

//insertion sort
void sortData(double data[], int size){
    for (int i = 0; i < size; ++i){
        double temp = data[i];
        for (int j = i-1; j >= 0; --j){
            if (data[j] < temp ){
                data[j+1] = data[j];
            } else {
                data[j+1] = temp;
                break;
            }
            if (j == 0){
                data[j] = temp;
            }
        }
    }
    return;
}

void sortCountriesByGHG(Country data[], int size){
   //SORT THE COUNTRIES BY GREENHOUSE GAS EMISSIONS
      for (int i = 0; i < size; ++i){
        Country temp = data[i];
        for (int j = i-1; j >= 0; --j){
            if (data[j].ghg < temp.ghg ){
                data[j+1] = data[j];
            } else {
                data[j+1] = temp;
                break;
            }
            if (j == 0){
                data[j] = temp;
            }
        }
    }
    return;
}

void sortCountriesByGHGperCap(Country data[], int size){
    //SORT THE COUNTRIES BY GREENHOUSE GAS EMISSIONS PER CAPITA
       for (int i = 0; i < size; ++i){
        Country temp = data[i];
        for (int j = i-1; j >= 0; --j){
            if (data[j].ghg/data[j].pop < temp.ghg/temp.pop ){
                data[j+1] = data[j];
            } else {
                data[j+1] = temp;
                break;
            }
            if (j == 0){
                data[j] = temp;
            }
        }
    }
    return;
}

void sortCountriesByRE(Country data[], int size){
    //SORT THE COUNTRIES BY ELECTRICITY GENERATED BY RENEWABLE SOURCES
          for (int i = 0; i < size; ++i){
        Country temp = data[i];
        for (int j = i-1; j >= 0; --j){
            if (data[j].renewable < temp.renewable){
                data[j+1] = data[j];
            } else {
                data[j+1] = temp;
                break;
            }
            if (j == 0){
                data[j] = temp;
            }
        }
    }
    return;
}

void sortCountriesByREperCap(Country data[], int size){
    //SORT THE COUNTRIES BY ELECTRICITY GENERATED BY RENEWABLE SOURCES PER CAPITA
       for (int i = 0; i < size; ++i){
        Country temp = data[i];
        for (int j = i-1; j >= 0; --j){
            if (data[j].renewable/data[j].pop < temp.renewable/temp.pop){
                data[j+1] = data[j];
            } else {
                data[j+1] = temp;
                break;
            }
            if (j == 0){
                data[j] = temp;
            }
        }
    }
    return;
}


int main() {

   Country allData[NUM_COUNTRIES];
   
   FILE* myFile = fopen("countryData.txt","r");
   char titles[30];
   fscanf(myFile, "%s %s %s %s", titles, titles, titles, titles);
   fscanf(myFile, "%s %s %s %s", titles, titles, titles, titles);
   fscanf(myFile, "%s %s %s %s", titles, titles, titles, titles);
   fscanf(myFile, "%s %s %s %s", titles, titles, titles, titles);
   
   for (int i = 0; i < NUM_COUNTRIES; ++i) {
      fscanf(myFile,"%s %s %lf %lf", allData[i].code, allData[i].name, &allData[i].ghg, &allData[i].co2);
      fscanf(myFile,"%lf %lf %lf %lf", &allData[i].ch4, &allData[i].n2o, &allData[i].pop, &allData[i].gdp);
      fscanf(myFile,"%lf %lf %lf %lf", &allData[i].consumption, &allData[i].generation, &allData[i].renewable, &allData[i].hydro);
      fscanf(myFile,"%lf %lf %lf %lf", &allData[i].wind, &allData[i].biomass, &allData[i].solar, &allData[i].geothermal);
   }
   
   char mycode[4] = "USA";
   printf("CODE   COUNTRY_NAME\n");
   for (int i = 0; i < NUM_COUNTRIES; ++i) {
      printf("%s    %s\n",allData[i].code, allData[i].name);  
   }
   while (strcmp(mycode, "END") != 0) {
      printf("Enter a country CODE from the above list to print out its energy details [enter END to exit]...");
      scanf("%s",mycode);
   
      if (strcmp(mycode, "END") != 0) {
         int ind = findCountry(allData,mycode);
         if (ind >= 0) {
            printDetails(allData[ind]);
         }
      }
   }
   
   printf("\n");

   //FIRST, SORT THE COUNTRY DATA BY GREENHOUSE GAS EMISSIONS & REPORT THE TOP 10
   sortCountriesByGHG(allData, NUM_COUNTRIES);
   printf("The 10 countries with the most greenhouse gas emissions are:\n");
   for (int i = 0; i<10;  i++) {
      printf("#%d %s: %.2lf million-tonnes-of-CO2\n",i+1,allData[i].name,allData[i].ghg);
   }
   printf("\n");
   
   //NEXT, SORT BY GREENHOUSE GAS EMISSIONS PER CAPITA & REPORT THE TOP 10
   sortCountriesByGHGperCap(allData, NUM_COUNTRIES);
   printf("The 10 countries with the most greenhouse gas emissions per capita are:\n");
   for (int i = 0; i<10;  i++) {
      printf("#%d %s: %.2lf tonnes-of-C02/person\n",i+1,allData[i].name,allData[i].ghg/allData[i].pop*1000000);
   }
   printf("\n");

   //THEN, SORT BY ELECTRICITY GENERATED BY RENEWABLE SOURCES & REPORT THE TOP 10
   sortCountriesByRE(allData, NUM_COUNTRIES);
   printf("The 10 countries with the most electricity generation from renewable sources are:\n");
   for (int i = 0; i<10;  i++) {
      printf("#%d %s: %.2lf GWh\n",i+1,allData[i].name,allData[i].renewable);
   }
   printf("\n");

   //LAST, SORT BY ELECTRICITY GENERATED BY RENEWABLE SOURCES PER CAPITA & REPORT THE TOP 10
   sortCountriesByREperCap(allData, NUM_COUNTRIES);
   printf("The 10 countries with the most electricity generation from renewable sources per capita are:\n");
   for (int i = 0; i<10;  i++) {
      printf("#%d %s: %.2lf MWh/person\n",i+1,allData[i].name,allData[i].renewable/allData[i].pop*1000);
   }
   printf("\n");

   return 0;
}